'use clinet'
import React, {useEffect} from 'react';
import Head from 'next/head'

import { db } from '../services/firebase';
import { collection , getDocs } from 'firebase/firestore';

export default function Home() {

  useEffect(() => {
    const fetchData = async () => {
      const query = await getDocs(collection(db, "Food"));
      // query.forEach((doc) => {
      //   console.log(doc.data());
      // });
    };
  
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>안녕</h2>
    </>
  )
}
